### ISSUE TITLE
add a uilabel on cell

### ISSUE THREAD

**Issue by dreamgo** [mayuur/MJParallaxCollectionView#6]
I try to add a uilabel on each cell, but it doesn't work. What I did is 1. add uilabel to cell on storyboard, and hook it to MJCollectionViewCell.h 2. add cell.title.text=@"sdsdsd"; in cellForItemAtIndexPath:(NSIndexPath *)indexPath() ;

But it still doesn't work? what's wrong with my code? Thanks.

**Comment by mayuur** [comment]
What is the problem you face in adding a label?

**Comment by dreamgo** [comment]
Thanks for your reply. My problem is The UILabel can't be displayed. Could you supply a small demo for it?

**Comment by ehmadzubair** [comment]
I'm having the same problem... anything that i want to display white adding in the MJCollectionViewCell or in a subclass isn't appearing

**Comment by pahnev** [comment]
I've noticed that it's best to modify UICollectionViewCell in code. When you are doing both Storyboard is somewhat buggy with that.

I just tried this my self in MJCollectionViewCell.h and everything works as expected:

``` Objective-c
self.nameLabel = [[UILabel alloc] initWithFrame:CGRectMake(50, 50, 100, 100)];
    
[self addSubview:self.MJImageView];
[self.MJImageView addSubview:self.nameLabel];

```

**Comment by dreamgo** [comment]
Great !  Thanks for your help!

**Comment by mayuur** [comment]
Hey @dreamgo @ehmadzubair @pahnev the problem you were facing is MJImageView came above the things you added. 

In MJCollectionViewCell.m file, just add this line below initialization of MJImageView in the method setupImageView

``` Objective-c
[self sendSubviewToBack:self.MJImageView];
```

Like this : 

``` Objective-c
- (void)setupImageView
{
    // Clip subviews
    self.clipsToBounds = YES;

    // Add image subview
    self.MJImageView = [[UIImageView alloc] initWithFrame:CGRectMake(self.bounds.origin.x, self.bounds.origin.y, self.bounds.size.width, IMAGE_HEIGHT)];
    self.MJImageView.backgroundColor = [UIColor redColor];
    self.MJImageView.contentMode = UIViewContentModeScaleAspectFill;
    self.MJImageView.clipsToBounds = NO;
    [self addSubview:self.MJImageView];
    [self sendSubviewToBack:self.MJImageView];
}
```

Let me know if you face any other difficulty!

Keep coding! :)
